### ISSUE TITLE
Find a way to go from GDocs to JSON

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Day-Night#1]
We currently have [a basic sample of data on GDocs](https://docs.google.com/spreadsheets/d/1TbfHK1nAqDi6ucKUHGn9s5CUfts2XyO4DswPad8OGy4/edit#gid=0). We need to find a way to get from there to a json file that we can use on the map.
- [ ] list1
- [ ] list 2

**Comment by yuvadm** [comment]
Just commenting from the outside, this is probably what you guys are looking for :)

https://newsdev.github.io/driveshaft/

**Comment by mushon** [comment]
Thanks for the tip @yuvadm ;)
